---
- name: "apache | configtest | perform config test"
  ansible.builtin.command: apachectl configtest
  register: config_test
  changed_when: config_test.rc > 1000
  failed_when: config_test.rc > 0
  notify: reload {{ apache_name }}
