---
- name: "apache | import debian tasks"
  block:
    - name: "apache | debian | import specific tasks"
      ansible.builtin.import_tasks: debian/main.yml

    - name: "apache | debian | perform postinstall tasks"
      ansible.builtin.include_tasks: postinstall.yml
      vars:
        apache_vhost_tpl_folder: '/etc/apache2/sites-available/templates'
        apache_cfg_folder: '/etc/apache2/conf-available'
      tags:
        - install

    - name: "apache | debian | validate apache configuration"
      ansible.builtin.import_tasks: configtest.yml
      vars:
        apache_name: 'apache2'
      tags:
        - always

  when: ansible_distribution == 'Debian' or
        ansible_distribution == 'Ubuntu'
